---

- name: Install rabbitMQ
  apt: name=rabbitmq-server state=present
  tags: rabbitmq

- name: Add the rabbitMQ configuration
  template: src=rabbitmq-env.config.j2 dest=/etc/rabbitmq/rabbitmq-env.config
  notify: restart rabbitmq-server
  tags: rabbitmq

- file: path=/etc/rabbitmq/enabled_plugins state=file
  register: rabbitmq_management
  ignore_errors: True
  tags: rabbitmq

- name: Install rabbitMQ management
  shell: rabbitmq-plugins enable rabbitmq_management && service rabbitmq-server restart
  when: rabbitmq_management|failed
  tags: rabbitmq

- shell: rabbitmqadmin --help
  register: rabbitmq_admin
  ignore_errors: True
  no_log: True
  tags: rabbitmq

- include: rabbitmqadmin.yml
  when: rabbitmq_admin|failed
  tags: rabbitmq

