---

- name: Install rabbitMQ
  apt: name=rabbitmq-server state=present
  tags: rabbitmq

- file: src=/etc/rabbitmq/enabled_plugins state=file
  register: rabbitmq_management
  ignore_errors: True
  no_log: True
  tags: rabbitmq

- name: Install rabbitMQ management
  shell: rabbitmq-plugins enable rabbitmq_management && service rabbitmq-server restart
  when: rabbitmq_management|failed
  tags: rabbitmq

- shell: rabbitmqadmin --help
  register: rabbitmq_admin
  ignore_errors: True
  no_log: True
  tags: rabbitmq

- include: rabbitmqadmin.yml
  when: rabbitmq_admin|failed
  tags: rabbitmq

