---

- name: Install rabbitMQ Admin
  shell: wget http://guest:guest@192.168.56.190:55672/cli/rabbitmqadmin
  when: rabbitmq_management == ""

- name: Move the rabbitMQ Admin
  shell: mv rabbitmqadmin /usr/local/bin

- name: Make executable rabbitMQ Admin
  shell: chmod +x /usr/local/bin/rabbitmqadmin
  notify: restart rabbitmq-server